[DATE]

## What's changed

-  by @mch-sg in #1

<be>

## Supported versions
- Windows 7, 9, 10, 11
- macOS: `1.1.85, 1.1.86, 1.1.87, 1.1.88, 1.1.89, 1.1.90, 1.1.91, 1.1.92` 

<be>
**Full Changelog**: [`v1.2.4:2022 commits`](https://github.com/mch-sg/curo-dev/commits/main)
